# Задача 1
Получаем очищенный список слов в предложениях

In [86]:
import re
import numpy as np
from scipy.spatial.distance import cosine

In [57]:
file = open("sentences.txt", 'r')
string_list = list(file)
lowered_list = map(lambda x: x.lower(), string_list)

splitted_list = map(lambda x: re.split('[^a-z]', x) , lowered_list)

cleared_list = []
k = 0
for line in splitted_list:
    cleared_list.append([]) 
    for elem in line:
        if elem != '':
            cleared_list[k].append(elem)
    k = k+1

Получаем словарь, с подсчитанным количеством употреблений слов

In [58]:
dict = {}
for line in cleared_list:
    for word in line:
        count = dict.pop(word, -1)
        if count == -1:
            dict[word] = 1
        else:
            dict[word] = count + 1

Составляем таблицу:
    

Создайте матрицу размера n x d, где n — число предложений. Заполните ее: элемент с индексом (i, j) в этой матрице должен быть равен количеству вхождений j-го слова в i-е предложение. У вас должна получиться матрица размера 22 * 254.

In [80]:
max_Len = 0
for line in cleared_list:
    if max_Len < len(line):
        max_Len = len(line)
# print max_Len
# len(dict)

# 
tab = np.zeros((len(cleared_list),len(dict)))
tab.shape

word_list = dict.keys()

for k in range(len(cleared_list)):
    for l in range(len(word_list)):
        tab[k,l] = cleared_list[k].count(word_list[l])
print tab

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


Ищем косинусное расстояние

In [98]:
min1 = 10000
mini1 = 0
min2 = 10000
mini2 = 0
for k in range(1,22):
    if cosine(tab[0], tab[k]) <= min1:
        min2 = min1
        mini2 = mini1;
        min1 = cosine(tab[0], tab[k])
        mini1 = k
    elif cosine(tab[0], tab[k]) < min2:
        min2 = cosine(tab[0], tab[k])
        mini2 = k

print mini1
print min1
print mini2
print min2

6
0.7327387580875756
4
0.7770887149698589
